# OPERADORES RELACIONALES EN PYTHON 3

# EJEMPLOS

# ¿12 ES MAYOR QUE 16?

# ¿LA PALABRA 'PERRO' TIENE MENOS LETRAS QUE 'GATO' ?

# JUAN ESTA EN UNA DIETA PARA LLEGAR A SU PESO IDEAL DE 75 KG, SI PESA
# 70 KG O MENOS HABRA CUMPLIDO CON LA DIETA DEL NUTRICIONISTA.
# ¿JUAN CUMPLIO CON SU DIETA?


